
// autobahn_coordinate automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type AutobahnCoordinate struct {
    Lat string `json:"lat"`
    Long string `json:"long"`
}
