
// autobahn_charging_station_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type AutobahnChargingStationCollection struct {
    Entries []AutobahnChargingStation `json:"entries"`
}
