
// autobahn_parking_lorry_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type AutobahnParkingLorryCollection struct {
    Entries []AutobahnParkingLorry `json:"entries"`
}
