
// autobahn_charging_station automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type AutobahnChargingStation struct {
    Id string `json:"id"`
    Title string `json:"title"`
    Description []string `json:"description"`
    Coordinate *AutobahnCoordinate `json:"coordinate"`
}
