
// autobahn_closure_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type AutobahnClosureCollection struct {
    Entries []AutobahnClosure `json:"entries"`
}
