
// autobahn_warning_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type AutobahnWarningCollection struct {
    Entries []AutobahnWarning `json:"entries"`
}
