
// autobahn_warning automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


import "time"
type AutobahnWarning struct {
    Id string `json:"id"`
    Blocked bool `json:"blocked"`
    Future bool `json:"future"`
    Title string `json:"title"`
    Subtitle string `json:"subtitle"`
    Description []string `json:"description"`
    StartDate time.Time `json:"startDate"`
    Coordinate *AutobahnCoordinate `json:"coordinate"`
    LineString []AutobahnCoordinate `json:"lineString"`
}
