
// bundestag_member automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


import "time"
type BundestagMember struct {
    Id string `json:"id"`
    Name string `json:"name"`
    Party string `json:"party"`
    BioUrl string `json:"bioUrl"`
    State string `json:"state"`
    Constituency *BundestagConstituency `json:"constituency"`
    Elected string `json:"elected"`
    Photo string `json:"photo"`
    PhotoLarge string `json:"photoLarge"`
    PhotoLastChanged time.Time `json:"photoLastChanged"`
    LastChanged time.Time `json:"lastChanged"`
}
