
// bundestag_constituency automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type BundestagConstituency struct {
    Number string `json:"number"`
    Name string `json:"name"`
}
