
// BundesratTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    
    
    "github.com/apioo/sdkgen-go"
    
    "net/http"
    
    
)

type BundesratTag struct {
    internal *sdkgen.TagAbstract
}

func (client *BundesratTag) Member() *BundesratMemberTag {
    return NewBundesratMemberTag(client.internal.HttpClient, client.internal.Parser)
}




func NewBundesratTag(httpClient *http.Client, parser *sdkgen.Parser) *BundesratTag {
	return &BundesratTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
