
// BundesratMemberTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type BundesratMemberTag struct {
    internal *sdkgen.TagAbstract
}



// GetAll Returns all current members of the Bundesrat
func (client *BundesratMemberTag) GetAll() (BundesratMemberCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/bundesrat/member", pathParams))
    if err != nil {
        return BundesratMemberCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return BundesratMemberCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return BundesratMemberCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return BundesratMemberCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response BundesratMemberCollection
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return BundesratMemberCollection{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundesratMemberCollection{}, err
            }

            return BundesratMemberCollection{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundesratMemberCollection{}, err
            }

            return BundesratMemberCollection{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundesratMemberCollection{}, err
            }

            return BundesratMemberCollection{}, &MessageException{
                Payload: response,
            }
        default:
            return BundesratMemberCollection{}, errors.New("the server returned an unknown status code")
    }
}



func NewBundesratMemberTag(httpClient *http.Client, parser *sdkgen.Parser) *BundesratMemberTag {
	return &BundesratMemberTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
