
// BundestagMemberTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type BundestagMemberTag struct {
    internal *sdkgen.TagAbstract
}



// Get Returns specific member of the Bundestag
func (client *BundestagMemberTag) Get(memberId string) (BundestagMember, error) {
    pathParams := make(map[string]interface{})
    pathParams["member_id"] = memberId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/bundestag/member/:member_id", pathParams))
    if err != nil {
        return BundestagMember{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return BundestagMember{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return BundestagMember{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return BundestagMember{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response BundestagMember
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return BundestagMember{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundestagMember{}, err
            }

            return BundestagMember{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundestagMember{}, err
            }

            return BundestagMember{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundestagMember{}, err
            }

            return BundestagMember{}, &MessageException{
                Payload: response,
            }
        default:
            return BundestagMember{}, errors.New("the server returned an unknown status code")
    }
}

// GetAll Returns all current members of the Bundestag
func (client *BundestagMemberTag) GetAll() (BundestagMemberCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/bundestag/member", pathParams))
    if err != nil {
        return BundestagMemberCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return BundestagMemberCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return BundestagMemberCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return BundestagMemberCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response BundestagMemberCollection
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return BundestagMemberCollection{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundestagMemberCollection{}, err
            }

            return BundestagMemberCollection{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundestagMemberCollection{}, err
            }

            return BundestagMemberCollection{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return BundestagMemberCollection{}, err
            }

            return BundestagMemberCollection{}, &MessageException{
                Payload: response,
            }
        default:
            return BundestagMemberCollection{}, errors.New("the server returned an unknown status code")
    }
}



func NewBundestagMemberTag(httpClient *http.Client, parser *sdkgen.Parser) *BundestagMemberTag {
	return &BundestagMemberTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
