
// bundesrat_member_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type BundesratMemberCollection struct {
    Entries []BundesratMember `json:"entries"`
}
