
// bundesrat_member automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


import "time"
type BundesratMember struct {
    HonorificTitle string `json:"honorificTitle"`
    FirstName string `json:"firstName"`
    Name string `json:"name"`
    Party string `json:"party"`
    State string `json:"state"`
    BundesratMember bool `json:"bundesratMember"`
    Member bool `json:"member"`
    Designated bool `json:"designated"`
    Url string `json:"url"`
    ImagePath string `json:"imagePath"`
    ImageDate time.Time `json:"imageDate"`
    Detail string `json:"detail"`
    Bio string `json:"bio"`
    Address string `json:"address"`
}
