
// BundestagTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    
    
    "github.com/apioo/sdkgen-go"
    
    "net/http"
    
    
)

type BundestagTag struct {
    internal *sdkgen.TagAbstract
}

func (client *BundestagTag) Member() *BundestagMemberTag {
    return NewBundestagMemberTag(client.internal.HttpClient, client.internal.Parser)
}




func NewBundestagTag(httpClient *http.Client, parser *sdkgen.Parser) *BundestagTag {
	return &BundestagTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
