
// CityTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type CityTag struct {
    internal *sdkgen.TagAbstract
}



// Get Returns a specific city
func (client *CityTag) Get(cityId string) (City, error) {
    pathParams := make(map[string]interface{})
    pathParams["city_id"] = cityId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/city/:city_id", pathParams))
    if err != nil {
        return City{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return City{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return City{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return City{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response City
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return City{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return City{}, err
            }

            return City{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return City{}, err
            }

            return City{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return City{}, err
            }

            return City{}, &MessageException{
                Payload: response,
            }
        default:
            return City{}, errors.New("the server returned an unknown status code")
    }
}

// GetAll Returns all available cities
func (client *CityTag) GetAll(startIndex int, state string, district string, name string, zipCode string) (CityCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})
    queryParams["startIndex"] = startIndex
    queryParams["state"] = state
    queryParams["district"] = district
    queryParams["name"] = name
    queryParams["zipCode"] = zipCode

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/city", pathParams))
    if err != nil {
        return CityCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return CityCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return CityCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return CityCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response CityCollection
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return CityCollection{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return CityCollection{}, err
            }

            return CityCollection{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return CityCollection{}, err
            }

            return CityCollection{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return CityCollection{}, err
            }

            return CityCollection{}, &MessageException{
                Payload: response,
            }
        default:
            return CityCollection{}, errors.New("the server returned an unknown status code")
    }
}



func NewCityTag(httpClient *http.Client, parser *sdkgen.Parser) *CityTag {
	return &CityTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
