
// city automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type City struct {
    Id int `json:"id"`
    State string `json:"state"`
    Rb string `json:"rb"`
    District string `json:"district"`
    Verb string `json:"verb"`
    Gem string `json:"gem"`
    ZipCode string `json:"zipCode"`
    Area int `json:"area"`
}
