
// Client automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    
    
    "github.com/apioo/sdkgen-go"
    
    
    
    
)

type Client struct {
    internal *sdkgen.ClientAbstract
}

func (client *Client) Warning() *WarningTag {
    return NewWarningTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) City() *CityTag {
    return NewCityTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) District() *DistrictTag {
    return NewDistrictTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) State() *StateTag {
    return NewStateTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Bundestag() *BundestagTag {
    return NewBundestagTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Bundesrat() *BundesratTag {
    return NewBundesratTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Autobahn() *AutobahnTag {
    return NewAutobahnTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Authorization() *AuthorizationTag {
    return NewAuthorizationTag(client.internal.HttpClient, client.internal.Parser)
}

func (client *Client) Meta() *MetaTag {
    return NewMetaTag(client.internal.HttpClient, client.internal.Parser)
}




func NewClient(baseUrl string, credentials sdkgen.CredentialsInterface) (*Client, error) {
	var client, err = sdkgen.NewClient(baseUrl, credentials)
    if err != nil {
        return &Client{}, err
    }

	return &Client{
		internal: client,
	}, nil
}

func Build(clientId string, clientSecret string, tokenStore sdkgen.TokenStoreInterface, scopes []string) (*Client, error) {
    var credentials = sdkgen.OAuth2{
        ClientId: clientId,
        ClientSecret: clientSecret,
        TokenUrl: "https://api.deutschland-api.dev/authorization/token",
        AuthorizationUrl: "",
        TokenStore: tokenStore,
        Scopes: scopes,
    }

    return NewClient("https://api.deutschland-api.dev/", credentials)
}

