
// collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type Collection[T any] struct {
    TotalResults int `json:"totalResults"`
    StartIndex int `json:"startIndex"`
    ItemsPerPage int `json:"itemsPerPage"`
    Entries []T `json:"entries"`
}
