
// district automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type District struct {
    Id string `json:"id"`
    State string `json:"state"`
    Type string `json:"type"`
    Name string `json:"name"`
    Nuts string `json:"nuts3"`
    Area int `json:"area"`
}
