
// DistrictTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type DistrictTag struct {
    internal *sdkgen.TagAbstract
}



// Get Returns a specific district
func (client *DistrictTag) Get(districtId string) (District, error) {
    pathParams := make(map[string]interface{})
    pathParams["district_id"] = districtId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/district/:district_id", pathParams))
    if err != nil {
        return District{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return District{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return District{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return District{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response District
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return District{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return District{}, err
            }

            return District{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return District{}, err
            }

            return District{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return District{}, err
            }

            return District{}, &MessageException{
                Payload: response,
            }
        default:
            return District{}, errors.New("the server returned an unknown status code")
    }
}

// GetAll Returns all available districts
func (client *DistrictTag) GetAll(startIndex int, state string, name string) (DistrictCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})
    queryParams["startIndex"] = startIndex
    queryParams["state"] = state
    queryParams["name"] = name

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/district", pathParams))
    if err != nil {
        return DistrictCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return DistrictCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return DistrictCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return DistrictCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response DistrictCollection
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return DistrictCollection{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return DistrictCollection{}, err
            }

            return DistrictCollection{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return DistrictCollection{}, err
            }

            return DistrictCollection{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return DistrictCollection{}, err
            }

            return DistrictCollection{}, &MessageException{
                Payload: response,
            }
        default:
            return DistrictCollection{}, errors.New("the server returned an unknown status code")
    }
}



func NewDistrictTag(httpClient *http.Client, parser *sdkgen.Parser) *DistrictTag {
	return &DistrictTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
