
// state automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


type State struct {
    Id string `json:"id"`
    Name string `json:"name"`
    Area int `json:"area"`
}
