
// StateTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app



import (
    
    "encoding/json"
    "errors"
    "github.com/apioo/sdkgen-go"
    "io"
    "net/http"
    "net/url"
    
)

type StateTag struct {
    internal *sdkgen.TagAbstract
}



// Get Returns a specific state
func (client *StateTag) Get(stateId string) (State, error) {
    pathParams := make(map[string]interface{})
    pathParams["state_id"] = stateId

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/state/:state_id", pathParams))
    if err != nil {
        return State{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return State{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return State{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return State{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response State
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return State{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return State{}, err
            }

            return State{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return State{}, err
            }

            return State{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return State{}, err
            }

            return State{}, &MessageException{
                Payload: response,
            }
        default:
            return State{}, errors.New("the server returned an unknown status code")
    }
}

// GetAll Returns all available states
func (client *StateTag) GetAll(startIndex int, name string) (StateCollection, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})
    queryParams["startIndex"] = startIndex
    queryParams["name"] = name

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/state", pathParams))
    if err != nil {
        return StateCollection{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("GET", u.String(), nil)
    if err != nil {
        return StateCollection{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return StateCollection{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return StateCollection{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var response StateCollection
        err = json.Unmarshal(respBody, &response)
        if err != nil {
            return StateCollection{}, err
        }

        return response, nil
    }

    switch resp.StatusCode {
        case 400:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return StateCollection{}, err
            }

            return StateCollection{}, &MessageException{
                Payload: response,
            }
        case 404:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return StateCollection{}, err
            }

            return StateCollection{}, &MessageException{
                Payload: response,
            }
        case 500:
            var response Message
            err = json.Unmarshal(respBody, &response)
            if err != nil {
                return StateCollection{}, err
            }

            return StateCollection{}, &MessageException{
                Payload: response,
            }
        default:
            return StateCollection{}, errors.New("the server returned an unknown status code")
    }
}



func NewStateTag(httpClient *http.Client, parser *sdkgen.Parser) *StateTag {
	return &StateTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
