
// warning automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


import "time"
type Warning struct {
    Id string `json:"id"`
    Severity string `json:"severity"`
    Urgency string `json:"urgency"`
    Type string `json:"type"`
    Title string `json:"title"`
    StartDate time.Time `json:"startDate"`
    ExpiresDate time.Time `json:"expiresDate"`
}
